### ISSUE TITLE
Dynamic Tabs, Excellent solution. Working now! But there is a warning.

### ISSUE THREAD

**Issue by jaywcjlove** [brentvatne/react-europe-2019-react-navigation#1]
@brentvatne I've implemented this solution but it results in a Yellowbox telling me I shouldn't render another navigator and links off to "common mistakes". It looks like you're disabling yellowboxes on this view, but I'd like to avoid that.

> You should only render one navigator explicitly in your app, and other navigators should be rendered by including them in that navigator. Full details at: https://reactnavigation.org/docs/common-mistakes.html#explicitly-rendering-more-than-one-navigator

I don't know if there is any way to solve this problem?

Thx!

**Comment by jaywcjlove** [comment]
This example: 

https://github.com/brentvatne/react-europe-2019-react-navigation/blob/5ccb336f994c42038f6ba4e99ff223e0aaf54790/sections/DynamicTabs.js#L1-L104

**Comment by jaywcjlove** [comment]
Thx! I used TabView to complete my goal.

https://github.com/brentvatne/react-europe-2019-react-navigation/blob/5ccb336f994c42038f6ba4e99ff223e0aaf54790/sections/TabView.js#L1-L107

**Comment by brentvatne** [comment]
in v5 of react-navigation we will support more dynamic navigation patterns naturally :) https://blog.expo.io/announcing-react-navigation-5-0-bd9e5d45569e
